feat: added preflight to homebrew

diff --git a/.chezmoidata/commands.yaml b/.chezmoidata/commands.yaml
--- a/.chezmoidata/commands.yaml
+++ b/.chezmoidata/commands.yaml
@@ -9,6 +9,11 @@ commands:
     - sudo ACCEPT_EULA=Y apt install -y
 
   brew:
+    preflight: |
+      if ! command -v brew &>/dev/null; then
+        echo "🍺 Homebrew not found. Installing..."
+        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
+      fi
     install:
     - brew install
 
